### ISSUE TITLE
Loaded Word document got changed unexpectedly 

### ISSUE THREAD

**Issue by SiL3NC3** [EvotecIT/OfficeIMO#15]
Hi,
I want to use an existing docx file as a template to generate a circular letter and save each file separately.

So the template documents is being loaded with the "readonly" parameter set to true and the "autosave" parameter to false:

          using (WordDocument document = WordDocument.Load(template, true, false))
          {...
          
                  document.Save(filepath);
          }

When the changes to the document (filled up placeholders) is done, the save function is called with a given new filepath.

Why is the source document (template) always being updated? This breaks my template.
Is the "readonly" option not working properly?

A separate SaveAS function would be helpful to fully prevent changes to the source file.

Thank you for any hint.

**Comment by PrzemyslawKlys** [comment]
Hi, it's related to:
- https://github.com/EvotecIT/OfficeIMO/issues/12

I saw @jordan-hemming trying to fix this in his fork https://github.com/EvotecIT/OfficeIMO/commit/57018e3b9581f50d8f687f1101742c9fc8974fc9, but I am not sure what's the current status of it. 

It's a known issue and something that needs to be fixed ;/ And yes, readonly seems to not working properly.

**Comment by jordan-hemming** [comment]
This is down to how Open-XML-SDK handles SaveAs ([see issue #1139](https://github.com/OfficeDev/Open-XML-SDK/issues/1139)). An upstream fix does not seem likely.

My fork works around this by always using working with a WordprocessingDocument loaded from a MemoryStream, rather than directly from the disk. Some extra faffing about is then required to ensure that the file lock is still held to pass the IsFileLocked portions of the unit tests.

I'm happy to open a pull request with my changes. I didn't previously as I'm not sure if there are any significant performance penalties for doing it this way. It doesn't seem like it but I haven't tested it extensively.

**Comment by PrzemyslawKlys** [comment]
This project focus is:
- get things working
- look at performance optimizations later on

To make it easy for people to use functionality certain things will take a bit more time performance-wise and I'm ok with this. IF you really want it to be super optimized you can probably get better results by using Open-XML-SDK directly. For now, I won't even think that something takes 30ms more because that's not my goal. 

Feel free to submit PRs for anything that makes this library better so it's easier to use. Let's not worry about premature optimization.

**Comment by PrzemyslawKlys** [comment]
PR https://github.com/EvotecIT/OfficeIMO/pull/16 of @jordan-hemming was pushed. Hopefully this fixes your issue. If it doesn't please let me know.
