### ISSUE TITLE
How to display the specific gravity value in a pie chart

### ISSUE THREAD

**Issue by zzwh** [EvotecIT/OfficeIMO#218]
The chart needs to display the numerical values (proportion), but no implementation has been found in the current code
Document AddCoverPage (CoverPageTemplate. OnDark);
How to configure the company address and year parameters?
Additionally, all dependency libraries are relatively old

Machine translation, so...

**Comment by PrzemyslawKlys** [comment]
1. I dunno
2. CoverPages needs improvement to allow easier modifications, otherwise it's pain and you have to resort to playing openxml
3. Dependencies for SixLabors ImageSharp are on the highest non-paid version and will stay like that unless something happens
4. Dependencies for OpenXML SDK are not yet upgraded as I'm waiting for ClosedXML project to fix theirs. PR is ready on my end (https://github.com/EvotecIT/OfficeIMO/pull/195) but unless ClosedXML changes, I will continue with old version. There are no changes that would force me to change as is.

**Comment by zzwh** [comment]
Thank you very much for your hard work and dedication
I really like this work
Looking forward to an early update
