### ISSUE TITLE
WordParagraph.Style can throw an exception

### ISSUE THREAD

**Issue by ChrisBellBO** [EvotecIT/OfficeIMO#236]
I have a Word document with some custom styles. When I access the Style property on a paragraph using one of those styles, an exception is thrown. Maybe the enumerated type just needs a Custom value for anything non standard?

**Comment by PrzemyslawKlys** [comment]
Sure, there should be Custom set, if it can't match any of known types. Later on we should probably allow some easy custom styles reading/building. Care for PR?

**Comment by ChrisBellBO** [comment]
Sure thing. I've not contributed to github projects before so you may need to provide some guidance as to how to do that

**Comment by PrzemyslawKlys** [comment]
Fork the project so that it's in your name. Once it's in your name (not EvotecIT\OfficeIMO) you simply open it in Visual Studio using button. You do changes, you commit. They get into your fork. Once you will be happy you simply open PR from your fork. As long as PR is open you can just commit changes to your fork and it will appear in the PR.
