### ISSUE TITLE
How to access all of document contents in correct order?

### ISSUE THREAD

**Issue by ChrisBellBO** [EvotecIT/OfficeIMO#239]
Hi, I'm looking to use OfficeIMO to import Word documents to another format. I've fairly quickly been able to pull in the text content of a document with the correct structure but I'm now looking at importing tables and images (and any other content). I can see WordParagraph has an IsImage property which I think will give me what I want for images. For tables, I can see there is a Tables property on WordSection but nothing on WordParagraph. Is it possible to figure out where the table is within the document? I've looked at using the OpenXML API directly but that has just made me aware of why you developed this!

**Comment by PrzemyslawKlys** [comment]
It's hard in its current state because of how it was implemented, where Tables and a few other types are stored totally separate from Paragraphs. As in Table exists in Document directly, similar to Paragraphs, but Images, HyperLinks and others are bound to Paragraph. So I basically bound Paragraphs to Section, same with Table and so on, but this causes issues when trying to establish the order. 

I believe we need to create another Property which stores all Paragraphs, All Tables etc in single List in proper order as they are read from the word which should help with maintaining the current order without touching current properties. 

It shouldn't be too hard to add. Most of the code is ready in:
- https://github.com/EvotecIT/OfficeIMO/blob/master/OfficeIMO.Word/WordSection.PrivateMethods.cs

It just requires merging Lists/StBlocks/Paragraphs etc in one big ordered list of things. 

Especially since I wanted to create a library DocX to PDF, but without order it's hard ;)

**Comment by PrzemyslawKlys** [comment]
I think we should start somewhere, and improve over time. The methods in WordSection are simply converting OpenXml objects int officeimo objects for easier management so they convert Paragraph to WordParagraph, which then you can check if it has image, hyperlink or whatever assigned to them.

**Comment by PrzemyslawKlys** [comment]
Solved by: https://github.com/EvotecIT/OfficeIMO/pull/240
