### ISSUE TITLE
Change table width

### ISSUE THREAD

**Issue by ExtremeKaos** [EvotecIT/OfficeIMO#29]
New feature:
Looking for docs in https://evotec.xyz/docs/adding-tables-with-built-in-styles-managing-borders/, havent found a way to change width of table on/after creation. If doc margins change, table dont fill all documents width.

Is any way to do this using OfficeIMO ?

I will try to extend it by WordDocument.PublicMethods.cs, AddTable, if i dont miss something.

**Comment by PrzemyslawKlys** [comment]
Hi, I don't believe it's added yet. I guess one would add properties to `WordTable` class. There's already `_tableProperties`  property, which would just need some expansion. I guess we also need AutoFit/Fixed or whatever that is called in Word to be possible for user to choose. 

- https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.tablewidth?view=openxml-2.8.1
- https://docs.microsoft.com/en-us/office/open-xml/working-with-wordprocessingml-tables
- http://officeopenxml.com/WPtableLayout.php

So AddTable can be extended, but WordTable class needs updates so that it's not just basic setting that you set when adding table but something you can do on Load as well.

**Comment by PrzemyslawKlys** [comment]
- Some work in progress: https://github.com/EvotecIT/OfficeIMO/pull/30
