### ISSUE TITLE
Modify .csproj file for multi platform compatibility

### ISSUE THREAD

**Issue by byteSamurai** [EvotecIT/OfficeIMO#77]
At the moment, macOS users are not able to run the this project, due to a lack of target frameworks on their platforms and missing dependencies, e.g. the Test project requires a line like this:

```xml
<PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.4.0" Condition="$([MSBuild]::IsOsPlatform('OSX'))" />
```

Definition of Done:
- Project configuration has been tested on Windows in Visual Studio and VS code (Omnisharp)
- Project configuration has been tested on Mac in Visual Studio and VS code (Omnisharp)
- Project configuration has been tested on Linux in VS code (Omnisharp)

**Comment by PrzemyslawKlys** [comment]
I am not 100% sure what developers use daily and how quickly they forget about .NET. Since there's no more work or less work to be done to keep support for given framework I guess there is no harm to publish library in out of support framework? I guess any company that runs this is on their own, security wise and has their own processes. Unless there is a need to specifically code something different for NET 5 and NET 7 I would leave it as it is.

**Comment by PrzemyslawKlys** [comment]
Sure, we can remove .NET 5.0. Although you can always argue that if you had your app in NET 5.0 the vulnerability would be related to NET 5.0 and you running an unsupported product. Blaming everyone but yourself is a bit moot point. On the other hand, if it's part of the OfficeIMO problem, it will be present in all versions. 

To be honest, I am not really worried about NET 5.0 because, most likely if you use NET 5.0 you usually jump to new versions pretty soon to get all the cool stuff. I'm more worried about upcoming 3.1 end of life and that's why I hesitated. 

![image](https://user-images.githubusercontent.com/15063294/202874175-129ca017-9297-4f59-b2b6-0c9531caa8c7.png)

So you can remove NET 5.0 in the PR, but just a thought on the 3.1 which is LTS.
