### ISSUE TITLE
No way to adjust or create tab stops on WordParagraph objects

### ISSUE THREAD

**Issue by SprinterDave** [EvotecIT/OfficeIMO#89]
I don't see a way to adjust tab stops on a WordParagraph object.  Am I missing something?

**Comment by Workaholic01** [comment]
Hi Guys,

So is there a way to achieve this using Office IMO library. I am trying to create a header with tab spaced content e-g

Logo Image - 'Tab Space' - Contact Information - "Tab Space" - Some other info.

I am trying to achieve this using paragraph. But I am not able to do it. Any help would be appreciated.

**Comment by PrzemyslawKlys** [comment]
In my opinion, it's better to build this kind of stuff using the invisible table. You control the table size, the column sizes and it's perfectly planned. 

- See example https://github.com/EvotecIT/OfficeIMO/blob/master/OfficeIMO.Examples/Word/AdvancedDocument/AdvancedDocument.Create02.cs

At least that's how I do it manually when using Word, I have never seen anyone using TabSpaces to position stuff in Word, but maybe I am wrong.

**Comment by Workaholic01** [comment]
Thank you for the quick response @PrzemyslawKlys.

Yes, I ended up going for the invisible table as well. And for new lines I tried it but unfortunately it didn't work.

**Comment by aknaton** [comment]
> I have never seen anyone using TabSpaces to position stuff in Word, but maybe I am wrong.

I have used tabs in Word. A lot. But I have worked professionally as a technical writer. Right now though I have the same problem as @Workaholic01 so I may also use the workaround.

**Comment by PrzemyslawKlys** [comment]
Can any of you send me a small template (docx) with minimal amount of data that shows the use case? While I can add myself some tab stops I dont understand how would you use them so on design side of things I am not sure what would be right way. Also if you have some "idea" in dummy code how would you like to use it - it would be cool.

**Comment by aknaton** [comment]
If you create a new document directly in the Word-app and go to the header
you can se that the program added an center tab in the middle of the text
area and a right tab at the right side of the text area (as is shown in my
attached file, if it is not removed). The same is true for the footer. I
guess this is because this is the default use case. It then is easy to add
a logo, a company name in the middle and maybe a pagination at the right.

Maybe it would be nice to have an option to replicate that:

var head =
document.Sections[0].Header.Default.AddParagraphWithDefaultTabstops();

Usable for headers and footers.

Another usage I see is if you should construct an area where some people
should sign a document. See the attached file.

I don't know if one could do something similar have some sort of default
tab stops if one don't want to implement a full tab implementation in your
library.


Den tis 28 feb. 2023 kl 13:35 skrev Przemysław Kłys <
***@***.***>:

**Comment by PrzemyslawKlys** [comment]
I will probably go for full implementation, I just need to understand use cases. I see other "vendors" do it like this so I guess I will sort of replicate more or less. 

![image](https://user-images.githubusercontent.com/15063294/221882738-97547510-2dc1-4d50-b9e1-8e7278b5584d.png)

Although I am not sure I understand all functionality :-)

**Comment by PrzemyslawKlys** [comment]
Btw the examples/docs were stripped out

**Comment by PrzemyslawKlys** [comment]
So I have added a PR with both DefaultTabStop which is set to 720 (it was kind of always there), but then you can also add tab stops to paragraphs. Please remember that WordParagraph is basically a Run, which means even tho there are 5 WordParagraphs, it's actually 2 Paragraphs, that contain 5 runs, and that means if you ask 3rd,4th and 5th WordParagraph for TabStops it will have them exactly the same because in this case they are sharing single Paragraph/ParagraphProperties.

```cs
internal static void Example_BasicTabStops(string folderPath, bool openWord) {
    Console.WriteLine("[*] Creating standard document with paragraphs");
    string filePath = System.IO.Path.Combine(folderPath, "Basic Document with some tab stops.docx");
    using (WordDocument document = WordDocument.Create(filePath)) {
        var paragraph = document.AddParagraph("\tFirst Line");

        document.Settings.DefaultTabStop = 2880;
        document.Settings.CharacterSpacingControl = CharacterSpacingValues.DoNotCompress;

        Console.WriteLine("Tabs count: " + paragraph.TabStops.Count);

        var tab1 = paragraph.AddTabStop(1440);

        var tab2 = paragraph.AddTabStop(1440);
        tab2.Alignment = TabStopValues.Left;
        tab2.Leader = TabStopLeaderCharValues.Hyphen;
        tab2.Position = 1440;

        paragraph.AddText("\tMore text");

        Console.WriteLine($"Tabs count: " + paragraph.TabStops.Count);

        var paragraph1 = document.AddParagraph("\tNext Line");

        var tab3 = paragraph1.AddTabStop(5000);
        tab3.Leader = TabStopLeaderCharValues.Hyphen;

        var tab4 = paragraph1.AddTabStop(1440 * 2);
        paragraph1.AddText("\tEven more text");

        Console.WriteLine("Tabs for Paragraph2 count: " + paragraph.TabStops.Count);
        Console.WriteLine("Tabs for Paragraph1 count: " + paragraph1.TabStops.Count);
        Console.WriteLine("Default tab stop: " + document.Settings.DefaultTabStop);
        Console.WriteLine("Default tab stop: " + document.Settings.CharacterSpacingControl);

        document.Save();
    }

    using (WordDocument document = WordDocument.Load(filePath)) {

        document.Save(openWord);
    }
}
```

Maybe it needs further improvements, but this is what I came up with.
